
package com.qas.ondemand_2011_03;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QASOnDemandIntermediary", targetNamespace = "http://www.qas.com/OnDemand-2011-03", wsdlLocation = "https://ws3.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?wsdl")
public class QASOnDemandIntermediary
    extends Service
{

    private final static URL QASONDEMANDINTERMEDIARY_WSDL_LOCATION;
    private final static WebServiceException QASONDEMANDINTERMEDIARY_EXCEPTION;
    private final static QName QASONDEMANDINTERMEDIARY_QNAME = new QName("http://www.qas.com/OnDemand-2011-03", "QASOnDemandIntermediary");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws3.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QASONDEMANDINTERMEDIARY_WSDL_LOCATION = url;
        QASONDEMANDINTERMEDIARY_EXCEPTION = e;
    }

    public QASOnDemandIntermediary() {
        super(__getWsdlLocation(), QASONDEMANDINTERMEDIARY_QNAME);
    }

    public QASOnDemandIntermediary(WebServiceFeature... features) {
        super(__getWsdlLocation(), QASONDEMANDINTERMEDIARY_QNAME, features);
    }

    public QASOnDemandIntermediary(URL wsdlLocation) {
        super(wsdlLocation, QASONDEMANDINTERMEDIARY_QNAME);
    }

    public QASOnDemandIntermediary(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QASONDEMANDINTERMEDIARY_QNAME, features);
    }

    public QASOnDemandIntermediary(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QASOnDemandIntermediary(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QAPortType
     */
    @WebEndpoint(name = "QAPortType")
    public QAPortType getQAPortType() {
        return super.getPort(new QName("http://www.qas.com/OnDemand-2011-03", "QAPortType"), QAPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QAPortType
     */
    @WebEndpoint(name = "QAPortType")
    public QAPortType getQAPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.qas.com/OnDemand-2011-03", "QAPortType"), QAPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QASONDEMANDINTERMEDIARY_EXCEPTION!= null) {
            throw QASONDEMANDINTERMEDIARY_EXCEPTION;
        }
        return QASONDEMANDINTERMEDIARY_WSDL_LOCATION;
    }

}
